import type { Metadata } from "next";
import "./globals.css";
import Providers from "./utils/provider";

export const metadata: Metadata = {
  title: "Marathon - Weather Channel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-mono p-8 sm:p-24">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
